version: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - revive
    - goconst
    - gocritic
    - unconvert

formatters:
  disable-all: true
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/ArjenSchwarz/awstools
  revive:
    severity: warning
    enable-all-rules: false
    rules:
      - name: blank-imports
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: exported
      - name: indent-error-flow
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - testdata
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0