on: [push, pull_request]

jobs:
  test:
    name: Build binary
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: ${{ matrix.go-version }}
    - name: Do a build
      run: go build -o awstools