on: push
name: Build and Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - uses: actions/checkout@master
    - name: Build
      env:
        GOPATH: /home/runner/go
      run: make build
    - name: Package
      if: github.ref == '/refs/head/master'
      run: make package
    - name: Deploy
      if: github.ref == '/refs/head/master'
      uses: ArjenSchwarz/actions/github/release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOURCE_PATH: dist
        VERSION: latest
      with:
        args: -delete
