on: push
name: Build and Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - uses: actions/checkout@master
    - name: Build
      run: make build
    - name: Package
      # if: contains( github.ref, '/refs/head/master' )
      # uses: ArjenSchwarz/actions/utils/zip@master
      run: make package
      # with:
      #   entrypoint: make
      #   args: package
    - name: Deploy
      if: contains( github.ref, '/refs/head/master' )
      uses: ArjenSchwarz/actions/github/release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOURCE_PATH: dist
        VERSION: latest
      with:
        args: -delete
