on: push
name: Build and Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: apex/actions/go@master
      with:
        entrypoint: make
        args: build
    - name: Package
      uses: ArjenSchwarz/actions/utils/zip@master
      with:
        entrypoint: make
        args: package
    - name: Deploy
      uses: ArjenSchwarz/actions/github/release@master
      if: endsWith( github.ref, "master" )
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOURCE_PATH: dist
        VERSION: latest
      with:
        args: -delete
